文学网站-V1.0/app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms.validators import DataRequired, Length


class CommentForm(FlaskForm):
    # 分类表单
    content = TextAreaField('分类名称', validators=[
        DataRequired(message="不能为空"), 
        Length(max=200, message="不符合字数要求！")
    ])

文学网站-V1.0/app/admin/views.py
from ctypes import pointer
from flask import (
    Blueprint, render_template, request, 
    flash, redirect, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash
from RealProject import db
from app.auth.views.auth import login_required
from app.blog.models import Category, Post, Tag, Comment, inspect_post
from app.auth.models import User
from .models import Banner
from .forms import CategoryForm, PostForm, TagForm, CreateUserForm, InspectPostForm
from flask import Blueprint, flash, render_template, request, redirect, url_for, session, g

bp = Blueprint('admin', __name__, url_prefix='/admin', 
    static_folder='static', template_folder='templates')


@bp.route('/')
@login_required
def index():
    post_count = Post.query.count()
    user_count = User.query.count()
    return render_template('admin/index.html', post_count=post_count, user_count=user_count)

@bp.route('/inspect')
@login_required
def inspect():
    # 文章审核
    post_count = Post.query.count()
    user_count = User.query.count()
    return render_template(
        'admin/inspect.html', post_count=post_count, user_count=user_count)


@bp.route('/article_inspect')
@login_required
def article_inspect():
    # 板块文章审核
    page = request.args.get('page', 1, type=int)
    pagination = inspect_post.query.order_by(-inspect_post.add_date).paginate(
        page=page, per_page=10, error_out=False)
    post_list = pagination.items
    for post in post_list:
        print(post.title)
    print(g.user.inspect)
    return render_template(
        'admin/article_inspect.html', 
        post_list=post_list, pagination=pagination, inspect=g.user.inspect)


@bp.route('/article_detail/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_detail(post_id):
    post = inspect_post.query.get_or_404(post_id)
    form = InspectPostForm(
        title=post.title,
        desc=post.desc,
        category_id=post.category_id,
        content=post.content,
    )
    form.category_id.choices = [(v.id, v.name) for v in Category.query.all()]
    
    if form.validate_on_submit():
        P = Post(
                title=form.title.data,
                desc=form.desc.data,
                category_id=int(form.category_id.data),  # 一对多保存
                content=form.content.data,
                user_id=inspect_post.query.filter(inspect_post.id == post_id).first().user_id
        )

        db.session.add(P)
        post.is_pass = True
        post.is_inspect = True
        db.session.commit()
        flash(f'{form.title.data}审核成功，请为文章添加标签')  

        if g.user.is_super_user:
            return redirect(url_for('admin.article'))
        else:
            return redirect(url_for('admin.article_alter'))  

    return render_template(
        'admin/article_detail.html', 
        post=post, form=form
    )

@bp.route('/article_fail/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_fail(post_id):
    post = inspect_post.query.get_or_404(post_id)
    title = post.title

    post.is_pass = False
    post.is_inspect = True
    db.session.commit()
    flash(f'{title}审核成功')  
    if g.user.is_super_user:
        return redirect(url_for('admin.article'))
    else:
        return redirect(url_for('admin.article_alter')) 

@bp.route('/article_alter')
@login_required
def article_alter():
    # 查看文章列表
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(Post.category_id==g.user.inspect) \
    .order_by(Post.add_date).paginate(page, per_page=10, error_out=False)
    post_list = pagination.items
    inspect = g.user.inspect
    return render_template(
        'admin/article_alter.html', 
        post_list=post_list, 
        pagination=pagination,
        inspect=inspect
    )


@bp.route('/category')
@login_required
def category():
    # 查看分类
    page = request.args.get('page', 1, type=int)
    pagination = Category.query.order_by(
        -Category.add_date).paginate(
            page=page, per_page=10, error_out=False)
    category_list = pagination.items
    return render_template(
        'admin/category.html', 
        category_list=category_list, 
        pagination=pagination
    )


@bp.route('/category/add', methods=['GET', 'POST'])
@login_required
def category_add():
    # 新增文章分类
    form = CategoryForm()
    if form.validate_on_submit():
        name = Category.query.filter(Category.name==form.name.data)
        if name is None:
            category = Category(name=form.name.data, icon=form.icon.data)
            db.session.add(category)
            db.session.commit()
            flash(f'{form.name.data}分类添加成功')
            return redirect(url_for('admin.category'))
        else:
            flash(f'{form.name.data} 分类名重复')
            return redirect(url_for('admin.category_add'))
    return render_template('admin/category_form.html', form=form)


@bp.route('/category/edit/<int:cate_id>', methods=['GET', 'POST'])
@login_required
def category_edit(cate_id):
    # 编辑文章分类
    cate = Category.query.get(cate_id)
    form = CategoryForm(name=cate.name, icon=cate.icon)
    if form.validate_on_submit():
        cate.name = form.name.data
        cate.icon = form.icon.data
        db.session.add(cate)
        db.session.commit()
        flash(f'{form.name.data}分类修改成功')
        return redirect(url_for('admin.category'))
    return render_template('admin/category_form.html', form=form)


@bp.route('/category/delete/<int:cate_id>')
@login_required
def category_del(cate_id):
    cate = Category.query.get(cate_id)
    try:
        if cate:
            # 级联删除
            Post.query.filter(Post.category_id==cate.id).delete()
            db.session.delete(cate)
            db.session.commit()
            flash(f'{cate.name}分类删除成功')
            return redirect(url_for('admin.category'))
    except:
        flash(f'{cate.name} 分类下有很多文章，请先让版主清理文章后进行删除！')
        return redirect(url_for('admin.category'))

@bp.route('/article')
@login_required
def article():
    # 查看文章列表
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(-Post.add_date).paginate(
        page=page, per_page=10, error_out=False)
    post_list = pagination.items
    return render_template(
        'admin/article.html', 
        post_list=post_list, 
        pagination=pagination
    )


@bp.route('/article/add', methods=['GET', 'POST'])
@login_required
def article_add():
    # 新增文章
    form = PostForm()   
    form.category_id.choices = [(v.id, v.name) for v in Category.query.all()]
    form.tags.choices = [(v.id, v.name) for v in Tag.query.all()]
    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            desc=form.desc.data,
            has_type=form.has_type.data,
            category_id=int(form.category_id.data),  # 一对多保存
            content=form.content.data,
            user_id=g.user.id
        )
        post.tags = [Tag.query.get(tag_id) for tag_id in form.tags.data ]
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}添加成功')
        if g.user.is_super_user:
            return redirect(url_for('admin.article'))
        else:
            return redirect(url_for('admin.article_alter'))
    arr = ['none','茶余饭后', '风花雪月', '校园故事', '以诗会友']
    
    if g.user.inspect == None:
        index = 0
    else:
        index = g.user.inspect
    inspect = arr[index]

    return render_template('admin/article_form.html', form=form, flag=g.user.is_super_user,inspect=inspect)


@bp.route('/article/edit/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_edit(post_id):
    # 修改文章
    post = Post.query.get(post_id)
    tags = [tag.id for tag in post.tags]
    form = PostForm(
        title=post.title,
        desc=post.desc,
        category_id=post.category.id,
        has_type=post.has_type.value,
        content=post.content,
        tags=tags,
    )

    form.category_id.choices = [(v.id, v.name) for v in Category.query.all()]
    form.tags.choices = [(v.id, v.name) for v in Tag.query.all()]

    if form.validate_on_submit():
        # 这里才是修改的逻辑
        print(type(form.has_type.data))
        # 一个,引起的bug  StatementError
        post.title=form.title.data
        post.desc=form.desc.data
        post.has_type=form.has_type.data
        post.category_id=int(form.category_id.data)  # 一对多保存
        post.content=form.content.data
        post.tags=[Tag.query.get(tag_id) for tag_id in form.tags.data ]
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}修改成功')
        if g.user.is_super_user:
            return redirect(url_for('admin.article'))
        else:
            return redirect(url_for('admin.article_alter'))
    return render_template('admin/article_form.html', form=form, post=post, flag=g.user.is_super_user)


@bp.route('/article/delete/<int:post_id>')
@login_required
def article_del(post_id):
    # 删除文章
    post = Post.query.get(post_id)
    if post:
        db.session.delete(post)
        db.session.commit()
        flash(f'{post.title}删除成功')
        if g.user.is_super_user:
            return redirect(url_for('admin.article'))
        else:
            return redirect(url_for('admin.article_alter'))


@bp.route('/tag')
@login_required
def tag():
    # 查看标签列表
    page = request.args.get('page', 1, type=int)
    pagination = Tag.query.order_by(-Tag.add_date).paginate(page=page, per_page=10, error_out=False)
    tag_list = pagination.items
    return render_template('admin/tag.html', tag_list=tag_list, pagination=pagination)


@bp.route('/tag/add', methods=['GET', 'POST'])
@login_required
def tag_add():
    # 增加标签
    form = TagForm()
    if form.validate_on_submit():
        try:
            tag = Tag(name=form.name.data)
            db.session.add(tag)
            db.session.commit()
            flash(f'{form.name.data}添加成功')
            return redirect(url_for('admin.tag'))
        except:
            flash(f'{form.name.data} 重复标签名!')

文学网站-V1.0/app/blog/__init__.py
from .import views

文学网站-V1.0/app/blog/views.py
from flask import Blueprint, render_template, request, g, flash, redirect, url_for
from .models import Post, Category, Tag, Comment
from .forms import CommentForm
from RealProject import db

bp = Blueprint('blog', __name__, url_prefix='/blog', 
    static_folder='static', template_folder='templates')


def index():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(-Post.add_date).paginate(page=page, per_page=9, error_out=False)
    post_list = pagination.items

    import random
    imgs = [
        'https://scpic.chinaz.net/files/default/imgs/2023-06-08/d781fa28b7aa7db0.jpg', 
        'https://scpic.chinaz.net/files/pic/pic9/201406/apic4293.jpg', 
        'https://scpic.chinaz.net/files/pic/pic9/201909/zzpic20201.jpg']

    for post in post_list:
        post.img = random.sample(imgs, 1)[0]

    import json
    from app.admin.models import Banner
    banners = Banner.query.all()
    banners_list = [{'img': f'/admin/static/{banner.img}', 'url': banner.url} for banner in banners]
    banners_json = json.dumps(banners_list, ensure_ascii=False)
    return render_template('index.html', posts=post_list, pagination=pagination, banners=banners_json)


@bp.route('/category/<int:cate_id>')
def cates(cate_id):
    # 文章列表页
    cate = Category.query.get(cate_id)
    page = request.args.get('page', default=1, type=int)

    pagination = Post.query.filter(Post.category_id==cate_id).paginate(
        page=page, per_page=10, error_out=False)
    
    post_list = pagination.items

    return render_template(
        'cate_list.html', 
        post_list=post_list, 
        cate=cate,
        cate_id=cate_id,
        pagination=pagination)


@bp.route('/category/<int:cate_id>/<int:post_id>', methods=['GET', 'POST'])
def detail(cate_id, post_id):
    cate = Category.query.get(cate_id)
    post = Post.query.get_or_404(post_id)
    # 上一篇
    prev_post = Post.query.filter(Post.id < post_id).order_by(-Post.id).first()
    # 下一篇
    next_post = Post.query.filter(Post.id > post_id).order_by(Post.id).first()

    # 留言列表
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.filter(Comment.post_id==post.id).order_by(-Comment.add_date).paginate(
        page=page, per_page=10, error_out=False)
    comment_list = pagination.items
    
    # 留言功能
    form = CommentForm()
    # 验证表单数据
    if form.validate_on_submit():
        # 保存留言到数据库
        comment = Comment(
            content=form.content.data,
            post_id=post.id,
            user_id=g.user.id
        )
        db.session.add(comment)
        db.session.commit()
        # 传递成功信息
        flash(f'留言成功！')
        # 留言成功跳转到留言列表区
        return redirect(f"{url_for('blog.detail', cate_id=cate.id, post_id=post.id)}#comment")
    
    return render_template(
        'detail.html', cate=cate, post=post, 
        prev_post=prev_post, next_post=next_post, 
        pagination=pagination, comment_list=comment_list,
        form=form
    )


@bp.context_processor
def inject_archive():
    # 文章归档日期注入上下文
    posts = Post.query.order_by(-Post.add_date)
    dates = set([post.add_date.strftime("%Y年%m月") for post in posts])
    
    # 标签
    tags = Tag.query.all()
    for tag in tags:
        tag.style = ['is-success', 'is-danger', 'is-black', 'is-light', 'is-primary', 'is-link', 'is-info', 'is-warning']

    # 最新文章
    new_posts = posts.limit(6)
    return dict(dates=dates, tags=tags, new_posts=new_posts)


@bp.route('/category/<string:date>')
def archive(date):
    # 归档页
    import re
    # 正则匹配年月
    regex = re.compile(r'\d{4}|\d{2}')
    dates = regex.findall(date)
    
    from sqlalchemy import extract, and_, or_
    page = request.args.get('page', 1, type=int)
    # 根据年月获取数据
    archive_posts = Post.query.filter(
        and_(extract('year', Post.add_date) == int(dates[0]), 
            extract('month', Post.add_date) == int(dates[1])
            )
        )
    # 对数据进行分页
    pagination = archive_posts.paginate(page=page, per_page=5, error_out=False)
    return render_template('archive.html', 
        post_list=pagination.items,  pagination=pagination, date=date)


@bp.route('/tags/<int:tag_id>')
def tags(tag_id):
    # 标签页
    tag = Tag.query.get(tag_id)
    return render_template('tags.html', post_list=tag.post, tag=tag)


@bp.route('/search')
def search():
    # 搜索页
    words = request.args.get("words")
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(
        Post.title.like("%"+words+"%")).paginate(
            page=page, per_page=10, error_out=False)
    post_list = pagination.items
    return render_template('search.html', post_list=post_list, words=words, pagination=pagination)

文学网站-V1.0/app/blog/templates/archive.html
{% extends 'cate_list.html' %}

{% block title %}{{ date }}的文章归档 {% endblock title %}

{% block hero %}{% endblock hero %}

{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">首页</a></li>
            <li class="is-active"><a href="" aria-current="page">{{ date }}的归档</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}


{% block pagination %}
<nav class="pagination is-small" role="navigation" aria-label="pagination">
    {% if pagination.has_prev %}
        <a href="{{ url_for('blog.archive', date=date ) }}?page={{ pagination.prev_num }}" class="pagination-上一页" title="This is the first page">上一页</a>
    {% endif %}
    {% if pagination.has_next %}
        <a href="{{ url_for('blog.archive', date=date) }}?page={{ pagination.next_num }}" class="pagination-next">下一页</a>
    {% endif %}

    <ul class="pagination-list">        
        {% for page in pagination.iter_pages() %}
            {% if page %} 
                {% if page != pagination.page %}
                    <li>
                        <a href="{{ url_for('blog.archive', date=date) }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                    </li>
                {% else %}
                    <li>
                        <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                    </li>
                {% endif %}
            {% else %}
                <span class=pagination-ellipsis>&hellip;</span>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endblock pagination %}

文学网站-V1.0/app/blog/templates/base.html
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}济南大学_文学网站{% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/buefy.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/materialdesignicons.min.css') }}">
    {% block extra_head_style %}{% endblock extra_head_style %}   
</head>

<body>
    <div id="app" style="height:100%;">
        <div class="container is-fluid1" style="height:100%; ">
            <div class="is-block" style="height:100%;">
                <!-- 导航 -->
                {% block navbar %}     
                <template>
                    <b-navbar spaced shadow>
                        <template #brand>
                            <b-navbar-item>
                                <img src="{{ url_for('blog.static', filename='img/logo.png') }}" alt="文学网站">
                            </b-navbar-item>
                        </template>
                        <template #start>
                            <b-navbar-item href="/">
                                <strong>首页</strong>
                            </b-navbar-item>
                            
                            {% for cate in categorys %}
                            <b-navbar-item 
                                {% if cate.id == cate_id %} class="has-text-primary"{% endif %}
                                href="{{ url_for('blog.cates', cate_id=cate.id) }}">
                                <strong>{{ cate.name }}</strong>
                            </b-navbar-item>
                            {% endfor %}
                                
                        </template>

                        <template #end>
                            <b-navbar-item tag="div">
                                <!-- 判断用户是否已登录 -->
                                {% if g.user %}              
                                <div class=" buttons">
                                    <!-- 获取用户信息 -->
                                    <a class="button is-primary">欢迎您 {{ g.user['username'] }}</a>
                                    
                                    {% if g.user.is_super_user %}
                                        <a class="button is-success" href="{{ url_for('admin.index') }}">管理后台</a>
                                    {% elif not g.user.is_super_user and g.user.is_first_user or g.user.is_second_user or g.user.is_third_user or  g.user.is_fourth_user%}
                                        <a class="button is-success" href="{{ url_for('admin.inspect') }}">管理后台</a>
                                    {%endif%}

                                    <a class="button is-success" href="{{ url_for('auth.userinfo') }}">个人中心</a>
                                    <!-- 显示推出按钮 -->
                                    <a class="button is-danger" href="{{ url_for('auth.logout') }}">退出</a>
                                </div>
                                {% else %}
                                <!-- 用户未登录，显示登录注册按钮 -->
                                <div class="buttons">
                                    <a class="button is-primary" href="{{ url_for('auth.register') }}">
                                        <strong>注册</strong>
                                    </a>
                                    <a class="button is-light" href="{{ url_for('auth.login') }}">登录</a>
                                </div>
                                {% endif %}
                            </b-navbar-item>
                        </template>
                    </b-navbar>
                </template>
                {% endblock navbar %}
                <!-- 导航 end -->

                {% block main %} 
                <div class="box is-marginless is-shadowless is-radiusless">
                    {% block box %}
                    <div class="columns is-multiline">
                        {% for post in posts %}
                        <div class="column is-4-fullhd">
                            <div class="card">
                                <div class="card-image">
                                    <figure class="image is-4by3">
                                        <img src="{{ post.img }}"
                                            alt="Placeholder image">
                                    </figure>
                                </div>
                                <div class="card-content">
                                    <div class="media">
                                        <div class="media-content">
                                            <p class="title is-4">
                                                <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">
                                                    {{ post.title }}
                                                </a> 
                                                </p>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <p class=" has-text-grey is-size-7"> 
                                            {{ post.desc }}
                                        </p>
                                        <time datetime="{{ post.add_date }}">{{ post.add_date }}</time>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <nav class="pagination is-small" role="navigation" aria-label="pagination">
                        {% if pagination.has_prev %}
                        <a href="{{ url_for('index') }}?page={{ pagination.prev_num }}" class="pagination-上一页" title="This is the first page">上一页</a>
                        {% endif %}
                        {% if pagination.has_next %}
                        <a href="{{ url_for('index') }}?page={{ pagination.next_num }}" class="pagination-next">下一页</a>
                        {% endif %}
                    
                        <ul class="pagination-list">        
                            {% for page in pagination.iter_pages() %}
                                {% if page %} 
                                    {% if page != pagination.page %}
                                    <li>
                                        <a href="{{ url_for('index') }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                                    </li>
                                    {% else %}
                                    <li>
                                        <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                                    </li>
                                    {% endif %}
                                {% else %}
                                    <span class=pagination-ellipsis>&hellip;</span>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </nav>
                    {% endblock box %}
                </div>
                {% endblock main %}

                {% block footer %}      
                <div class="footer has-background-black-ter is-marginless">
                    <div class="has-text-centered has-text-grey-light">
                        <a class="has-text-grey-light" href="http://www.lotdoc.cn/blog/topic/detail/6/">济南大学_文学网站</a>
                    </div>
                </div>
                {% endblock footer %}
            </div>

        </div>
    </div>
    
    <script src="{{ url_for('blog.static', filename='js/vue.js') }}"></script>
    <script src="{{ url_for('blog.static', filename='js/buefy.min.js') }}"></script>

    {% block extra_foot_script %}{% endblock extra_foot_script %}
    <script>
        var app = new Vue({
            el: '#app',
            delimiters: ['{$', '$}'],
            data: {
                file:{},
                carousels:[],
                banners: []
            },
            methods: {}
        })
    </script>
    {% block vue_script %}{% endblock vue_script %}
</body>

</html>

文学网站-V1.0/app/blog/templates/cate_list.html
{% extends 'base.html' %}

{% block title %}{{ cate.name }}{% endblock title %}

{% block hero %}{% endblock hero %}

{% block box %}
<div class="columns">
    <div class="column is-9" style="border-right:solid 1px #eee ;">
        <div class="box is-shadowless has-background-light">
            {% block breadcrumb %}
            <nav class="breadcrumb is-small" aria-label="breadcrumbs">
                <ul>
                <li><a href="/">首页</a></li>
                <li class="is-active"><a href="#" aria-current="page">{{ cate.name }}</a></li>
                </ul>
            </nav>
            {% endblock breadcrumb %}
        </div>

        {% block cate_box %}
        {% for post in post_list %}
            <div class="pl-2">
                <h1 class="is-size-4">
                    <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">{{ post.title }}</a>
                </h1>
                <p class="has-text-grey-light is-size-6 mt-1">
                    <span class="icon"><i class="mdi mdi-clipboard-text-clock-outline"></i></span>{{ post.add_date }}
                    <span class="icon"><i class="mdi mdi-shape-outline"></i></span>{{ post.category.name }}
                    <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{ post.tags|join(',') }}
                </p>
                <div class="has-text-grey mt-1">{{ post.desc }}</div>
            </div>
            <div class=" dropdown-divider mb-3"></div>
        {% endfor %}
        {% block pagination %}
        <nav class="pagination is-small" role="navigation" aria-label="pagination">
            {% if pagination.has_prev %}
            <a href="{{ url_for('blog.cates', cate_id=cate.id ) }}?page={{ pagination.prev_num }}" class="pagination-上一页" title="This is the first page">上一页</a>
            {% endif %}
            {% if pagination.has_next %}
            <a href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ pagination.next_num }}" class="pagination-next">下一页</a>
            {% endif %}

            <ul class="pagination-list">        
                {% for page in pagination.iter_pages() %}
                    {% if page %} 
                        {% if page != pagination.page %}
                        <li>
                            <a href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ page }}" class="pagination-link" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                        {% else %}
                        <li>
                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">{{ page }}</a>
                        </li>
                        {% endif %}
                    {% else %}
                        <span class=pagination-ellipsis>&hellip;</span>
                    {% endif %}
                {% endfor %}

            </ul>
        </nav>
        {% endblock pagination %}
        {% endblock cate_box %}
    </div>
    <div class="column">
        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-search-web"></i></span>
                搜索
            </h1>
            <div class=" dropdown-divider"></div>
            <form action="{{ url_for('blog.search') }}" method="get">
                <div class="field has-addons">
                    <div class="control">
                    <input class="input" type="search" value="{{ words }}" name="words" placeholder="请输入关键字">
                    </div>
                    <div class="control">
                    <input type="submit" value="Search" class="button is-info">
                    </div>
                </div>
            </form>
        </div>

        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
                最新文章
            </h1>
            <div class=" dropdown-divider"></div>
            <ul>
                {% for post in new_posts %}
                <li class="pl-2">
                    <span class=" has-text-grey-light">{{ loop.index }}.</span> 
                    <a href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}">{{ post.title }}</a>
                </li>
                <div class="dropdown-divider"></div>
                {% endfor %}
            </ul>
        </div>

        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
                归档
            </h1>
            <div class=" dropdown-divider"></div>
            <ul>
                {% for date in dates %}
                <li class="pl-2"><a href="{{ url_for('blog.archive', date=date) }}">{{ date }}</a></li>
                <div class="dropdown-divider"></div>
                {% endfor %}
            </ul>
        </div>
        
        <div class="box is-shadowless" style="border:solid 1px #eee ;">
            <h1 class="is-size-6 icon-text">
                <span class="icon"><i class="mdi mdi-tag-multiple-outline"></i></span>
                标签
            </h1>
            <div class=" dropdown-divider"></div>
                <div class="tags">
                    {% for tag in tags %}
                    <a class="tag {{ tag.style|random() }}" href="{{ url_for('blog.tags', tag_id=tag.id) }}">{{ tag.name }}</a>
                    {% endfor %}
                </div>   
        </div>
    </div>
</div>
{% endblock box %}

文学网站-V1.0/app/blog/templates/tags.html
{% extends 'cate_list.html' %}

{% block title %}{{ tag }} {% endblock title %}

{% block hero %}{% endblock hero %}

{% block breadcrumb %}
    <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">首页</a></li>
            <li class="is-active"><a href="#" aria-current="page">{{ tag }}</a></li>
        </ul>
    </nav>
{% endblock breadcrumb %}

{% block pagination %}
{% endblock pagination %}